// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA68UKFqNDVA2jlakV9EHQB7GhxvR3tNBE',
    appId: '1:607188048170:web:531aa54af7ddf7680d2653',
    messagingSenderId: '607188048170',
    projectId: 'blog-flow-using-flutter',
    authDomain: 'blog-flow-using-flutter.firebaseapp.com',
    databaseURL: 'https://blog-flow-using-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blog-flow-using-flutter.firebasestorage.app',
    measurementId: 'G-EJ5NRJJQ4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDope-z57y4gR6rb9aOrjHLCy4-E5SUMFI',
    appId: '1:607188048170:android:debf99f4989848b60d2653',
    messagingSenderId: '607188048170',
    projectId: 'blog-flow-using-flutter',
    databaseURL: 'https://blog-flow-using-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blog-flow-using-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD14dpu4ItIUuG2LXVbvodKHEGje6zyIyo',
    appId: '1:607188048170:ios:84907088cd73b2790d2653',
    messagingSenderId: '607188048170',
    projectId: 'blog-flow-using-flutter',
    databaseURL: 'https://blog-flow-using-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blog-flow-using-flutter.firebasestorage.app',
    iosBundleId: 'com.example.blogAppFlutter',
  );
}
